-- ============================================
-- IPHONESHOP - SETUP COMPLETO DE BASE DE DATOS
-- ============================================

-- PASO 1: Eliminar tablas existentes si existen
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- PASO 2: Crear tablas

CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE products (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  "categoryId" TEXT REFERENCES categories(id) ON DELETE SET NULL,
  "initialStock" INTEGER DEFAULT 0,
  stock INTEGER DEFAULT 0,
  "minStock" INTEGER DEFAULT 10,
  unit TEXT DEFAULT 'Unidad',
  price DECIMAL(10,2) DEFAULT 0,
  "expirationDate" DATE,
  status TEXT DEFAULT 'Active',
  location TEXT,
  supplier TEXT,
  "imageUrl" TEXT,
  "imagePublicId" TEXT,
  brand TEXT,
  model TEXT,
  warranty TEXT,
  specifications TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'viewer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE transactions (
  id TEXT PRIMARY KEY,
  "productId" TEXT REFERENCES products(id) ON DELETE SET NULL,
  "productName" TEXT NOT NULL,
  type TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  reason TEXT,
  "user" TEXT,
  destination TEXT,
  receiver TEXT,
  attachment_name TEXT,
  attachment_url TEXT,
  attachment_type TEXT,
  attachment_size INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT,
  username TEXT,
  action TEXT NOT NULL,
  target_table TEXT,
  target_id TEXT,
  details JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- PASO 3: Crear índices
CREATE INDEX idx_products_category ON products("categoryId");
CREATE INDEX idx_products_code ON products(code);
CREATE INDEX idx_products_brand ON products(brand);
CREATE INDEX idx_transactions_product ON transactions("productId");
CREATE INDEX idx_transactions_date ON transactions(date);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at);

-- PASO 4: Insertar datos iniciales
INSERT INTO categories (id, name, description) VALUES
  ('cat_1', 'Smartphones', 'iPhone, Samsung, Google Pixel'),
  ('cat_2', 'Tablets', 'iPad, Samsung Tab, Surface'),
  ('cat_3', 'Laptops', 'MacBook, Surface, ThinkPad'),
  ('cat_4', 'Accesorios', 'Cables, cargadores, fundas'),
  ('cat_5', 'Audio', 'AirPods, audífonos, parlantes'),
  ('cat_6', 'Smartwatches', 'Apple Watch, Galaxy Watch');

INSERT INTO users (id, username, password, name, role) VALUES
  ('u1', 'admin', 'admin', 'Administrador', 'admin'),
  ('u2', 'vendedor', '123', 'Vendedor', 'viewer');

INSERT INTO products (
  id, code, name, description, "categoryId", 
  "initialStock", stock, "minStock", unit, price, 
  brand, model, warranty, status
) VALUES
  ('prod_1', 'IPH-15-PRO-256-TIT', 'iPhone 15 Pro', '256GB Titanio Natural',
    'cat_1', 15, 12, 5, 'Unidad', 1299.99, 'Apple', 'A2848', '12 meses', 'Active'),
  ('prod_2', 'IPH-15-128-BLU', 'iPhone 15', '128GB Azul',
    'cat_1', 20, 18, 8, 'Unidad', 899.99, 'Apple', 'A2846', '12 meses', 'Active'),
  ('prod_3', 'IPAD-AIR-M2-256', 'iPad Air M2', '256GB WiFi Space Gray',
    'cat_2', 10, 7, 3, 'Unidad', 749.99, 'Apple', 'MUWC3LL/A', '12 meses', 'Active'),
  ('prod_4', 'AIRPODS-PRO-2', 'AirPods Pro (2nd Gen)', 'USB-C Cancelación de ruido',
    'cat_5', 30, 22, 10, 'Unidad', 249.99, 'Apple', 'MTJV3AM/A', '12 meses', 'Active'),
  ('prod_5', 'MACBOOK-AIR-M3', 'MacBook Air M3', '15" 16GB RAM 512GB SSD',
    'cat_3', 8, 5, 2, 'Unidad', 1699.99, 'Apple', 'MRYN3LL/A', '12 meses', 'Active');

-- PASO 5: Desactivar RLS
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;

-- PASO 6: Verificar
SELECT 'Categorías' as tabla, COUNT(*) as registros FROM categories
UNION ALL SELECT 'Usuarios', COUNT(*) FROM users
UNION ALL SELECT 'Productos', COUNT(*) FROM products
UNION ALL SELECT 'Transacciones', COUNT(*) FROM transactions
UNION ALL SELECT 'Audit Logs', COUNT(*) FROM audit_logs;
